### ISSUE TITLE
Support launching server automatically from Emacs

### ISSUE THREAD

**Issue by wasamasa** [samrawal/emacs-secondmate#6]
There isn't really a reason why the server couldn't be launched automatically from Emacs. This requires figuring out a few things though:

- Locate a suitable Python interpreter.
- Locate the Python script relatively to the package file.
- Query the user for connection options if necessary (unless they set them explicitly).
- Pass those options to the Python script and launch it asynchronously.

The design for this can be lifted from other interaction packages, such as CIDER or Sly. See also #3.

Another thing worth thinking about is whether this really needs to use a HTTP service. If this is designed to run on localhost, talking with a subprocess makes a lot more sense and avoids security issues. I wrote a bunch before, though for interaction via Scheme rather than Emacs Lisp.

**Comment by samrawal** [comment]
The main reason I had the Language Model server and elisp functions separated was that for my use case -- and I figured for many others using this regularly -- I have Emacs running on my laptop and the server running on a separate, GPU-enabled machine. I think for users who do have a dedicated GPU machine separate from where they are running Emacs, this approach is better than running everything locally, with better latency, no significant consumption of CPU memory on their local machine (especially if using one of the larger models) and associated impact to battery life, etc.

The HTTP service-based architecture has the additional advantage that, if the user is using something like the HuggingFace Inference API, they can just plug that in instead of running a local server (abstracting this is on the TODO list).

I definitely see the advantages of launching the server automatically from Emacs, but the current architecture seems to be the most generalizable in supporting both use-cases of (1) running the Language Model server on a machine separate from the one running Emacs or (2) running both locally. If there are alternative suggestions I'm totally open to considering those though!

Thanks for all your help on this package :)
