### ISSUE TITLE
fine tuning?

### ISSUE THREAD

**Issue by vgoklani** [samrawal/emacs-secondmate#8]
Hey there,

thanks for sharing your work! Are you planning to fine-tune the model?

**Comment by samrawal** [comment]
Hi there! I've been thinking of fine-tuning on [The Pile GitHub subset](https://github.com/EleutherAI/github-downloader) -- EleutherAI/gpt-neo-2.7B is already trained on The Pile, but I was thinking of additional fine-tuning using the GitHub subset of the dataset to see if code generation quality improves.

Also, since the codebase uses the HuggingFace Transformers library, any model from the [Model Hub](https://huggingface.co) can be used as well -- there appear to be a few code generation models on there, although I haven't evaluated them.

It seems like there is some effort being done here as well -- https://github.com/ncoop57/gpt-code-clippy . 

And please let me know if you have any thoughts or suggestions on this!
